name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies (if needed)
        run: pip install -r requirements.txt  # Install dependencies from a requirements file

      - name: Run Python Script
        run: python full_automation.py  # Replace with the actual name of your Python script
