name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQL Server ODBC Driver (FreeTDS)
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc unixodbc-dev
          sudo apt-get install -y odbcinst
          sudo apt-get install -y tdsodbc freetds-dev freetds-bin

      - name: Configure SQL Server ODBC Driver (FreeTDS)
        run: |
          echo "[SQL Server]\nDescription = FreeTDS Driver\nDriver = /usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so" | sudo tee -a /etc/odbcinst.ini
      - name: Validate Driver Path
        run: |
          if [ -f "/usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so" ]; then
            echo "Driver file exists at the expected location."
          else
            echo "Driver file does not exist at the expected location!"
            # Optionally, search for it to determine its actual path:
            find /usr -name libtdsodbc.so
          fi
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Script
        env:
          DB_SERVER: 'TECH-99'
          DB_USERNAME: 'sa'
          DB_PASSWORD: '123456'
          DB_NAME: 'chem_prod_copy'
        run: python full_automation.py
