name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQL Server ODBC Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc unixodbc-dev
          sudo apt-get install -y odbcinst
          sudo apt-get install -y freetds-dev
          sudo apt-get install -y freetds-bin
          # Install Microsoft ODBC Driver for SQL Server
          sudo su -c "bash -c 'echo \"deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod focal main\" > /etc/apt/sources.list.d/mssql-release.list'"
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17

      - name: List ODBC Drivers
        run: |
          odbcinst -j
          odbcinst -q -d

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Script
        env:
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: python full_automation.py
